spring.application.name=faculty-service
server.port=${SERVER_PORT:8080}
spring.data.mongodb.uri=${MONGO_URI:mongodb://localhost:27017/facultydb}
app.jwt.secret=${JWT_SECRET:mysecretkey123}
app.jwt.expiry-ms=${JWT_EXPIRY_MS:36000000}
allowed.origins=${ALLOWED_ORIGINS:http://localhost:5173}